- hosts: orderer
  become: true
  become_user: root
  roles:
    - orderer

- hosts: peer
  become: true
  become_user: root
  roles:
    - couchdb

- hosts: peer
  become: true
  become_user: root
  roles:
    - peer 
