OrdererOrgs:
  - Name: Orderer
    Domain: freeexchange.cn
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
      
PeerOrgs:
  - Name: Org1
    Domain: org1.freeexchange.cn
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.freeexchange.cn
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

