- hosts: orderer
  tasks:
    - name: start
      shell: "systemctl start couchdb && ./start.sh"
      args:
        chdir: "{{ orderer_install_path }}"
- hosts: peer
  tasks:
    - name: start
      shell: "./start.sh"
      args:
        chdir: "{{ peer_install_path }}"
