- hosts: peer
  tasks:
    - name: stop
      shell: "./stop.sh && systemctl stop couchdb"
      args:
        chdir: "{{ peer_install_path }}"
- hosts: orderer
  tasks:
    - name: stop
      shell: "./stop.sh"
      args:
        chdir: "{{ orderer_install_path }}"
