- hosts: peer
  tasks:
    - name: stop 
      shell: "./stop.sh"
      args:
        chdir: "{{ peer_install_path }}"
    - name: delete files
      file: 
        path: "{{ peer_install_path }}"
        state: absent
    - name: delete cli
      file: 
        path: "{{ cli_install_path }}"
        state: absent
    - name: stop couchdb
      systemd:
          name: couchdb
          state: stopped
    - name: delete couchdb data
      file: 
        path: "{{ couchdb_data_path }}"
        state: absent
    
- hosts: orderer
  tasks:
    - name: stop
      shell: "./stop.sh"
      args:
        chdir: "{{ orderer_install_path }}"
    - name: delete files
      file: 
        path: "{{ orderer_install_path }}"
        state: absent
    - name: delete cli
      file: 
        path: "{{ cli_install_path }}"
        state: absent
